title: Joolowweng
description: ""
baseurl: ""
url: "https://joolowweng.github.io" # Your domain

# Build settings
markdown: kramdown
highlighter: rouge
theme: null
permalink: /:categories/:title/

# Exclude files from being included in the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .vscode

plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category-archive
  permalinks:
    category: /:name/
